package keyboard

import "github.com/openstadia/go-uinput"

var codeKey = map[string]uint16{
	// 3.1.1. Writing System Keys
	"Backquote":    uinput.KeyGrave,
	"Backslash":    uinput.KeyBackslash,
	"BracketLeft":  uinput.KeyLeftbrace,
	"BracketRight": uinput.KeyRightbrace,
	"Comma":        uinput.KeyComma,
	"Digit0":       uinput.Key0,
	"Digit1":       uinput.Key1,
	"Digit2":       uinput.Key2,
	"Digit3":       uinput.Key3,
	"Digit4":       uinput.Key4,
	"Digit5":       uinput.Key5,
	"Digit6":       uinput.Key6,
	"Digit7":       uinput.Key7,
	"Digit8":       uinput.Key8,
	"Digit9":       uinput.Key9,
	"Equal":        uinput.KeyEqual,
	"KeyA":         uinput.KeyA,
	"KeyB":         uinput.KeyB,
	"KeyC":         uinput.KeyC,
	"KeyD":         uinput.KeyD,
	"KeyE":         uinput.KeyE,
	"KeyF":         uinput.KeyF,
	"KeyG":         uinput.KeyG,
	"KeyH":         uinput.KeyH,
	"KeyI":         uinput.KeyI,
	"KeyJ":         uinput.KeyJ,
	"KeyK":         uinput.KeyK,
	"KeyL":         uinput.KeyL,
	"KeyM":         uinput.KeyM,
	"KeyN":         uinput.KeyN,
	"KeyO":         uinput.KeyO,
	"KeyP":         uinput.KeyP,
	"KeyQ":         uinput.KeyQ,
	"KeyR":         uinput.KeyR,
	"KeyS":         uinput.KeyS,
	"KeyT":         uinput.KeyT,
	"KeyU":         uinput.KeyU,
	"KeyV":         uinput.KeyV,
	"KeyW":         uinput.KeyW,
	"KeyX":         uinput.KeyX,
	"KeyY":         uinput.KeyY,
	"KeyZ":         uinput.KeyZ,
	"Minus":        uinput.KeyMinus,
	"Period":       uinput.KeyDot,
	"Quote":        uinput.KeyApostrophe,
	"Semicolon":    uinput.KeySemicolon,
	"Slash":        uinput.KeySlash,

	// 3.1.2. Functional Keys
	"AltLeft":      uinput.KeyLeftalt,
	"AltRight":     uinput.KeyRightalt,
	"Backspace":    uinput.KeyBackspace,
	"CapsLock":     uinput.KeyCapslock,
	"ContextMenu":  uinput.KeyCompose,
	"ControlLeft":  uinput.KeyLeftctrl,
	"ControlRight": uinput.KeyRightctrl,
	"Enter":        uinput.KeyEnter,
	"MetaLeft":     uinput.KeyLeftmeta,
	"MetaRight":    uinput.KeyRightmeta,
	"ShiftLeft":    uinput.KeyLeftshift,
	"ShiftRight":   uinput.KeyRightshift,
	"Space":        uinput.KeySpace,
	"Tab":          uinput.KeyTab,

	// 3.2. Control Pad Section
	"Delete":   uinput.KeyDelete,
	"End":      uinput.KeyEnd,
	"Help":     uinput.KeyHelp,
	"Home":     uinput.KeyHome,
	"Insert":   uinput.KeyInsert,
	"PageDown": uinput.KeyPagedown,
	"PageUp":   uinput.KeyPageup,

	// 3.3. Arrow Pad Section
	"ArrowDown":  uinput.KeyDown,
	"ArrowLeft":  uinput.KeyLeft,
	"ArrowRight": uinput.KeyRight,
	"ArrowUp":    uinput.KeyUp,

	// 3.4. Numpad Section
	"NumLock":        uinput.KeyNumlock,
	"Numpad0":        uinput.KeyKp0,
	"Numpad1":        uinput.KeyKp1,
	"Numpad2":        uinput.KeyKp2,
	"Numpad3":        uinput.KeyKp3,
	"Numpad4":        uinput.KeyKp4,
	"Numpad5":        uinput.KeyKp5,
	"Numpad6":        uinput.KeyKp6,
	"Numpad7":        uinput.KeyKp7,
	"Numpad8":        uinput.KeyKp8,
	"Numpad9":        uinput.KeyKp9,
	"NumpadAdd":      uinput.KeyKpplus,
	"NumpadDecimal":  uinput.KeyKpdot,
	"NumpadDivide":   uinput.KeyKpslash,
	"NumpadEnter":    uinput.KeyKpenter,
	"NumpadMultiply": uinput.KeyKpasterisk,
	"NumpadSubtract": uinput.KeyKpminus,

	// 3.5. Function Section
	"Escape": uinput.KeyEsc,
	"F1":     uinput.KeyF1,
	"F2":     uinput.KeyF2,
	"F3":     uinput.KeyF3,
	"F4":     uinput.KeyF4,
	"F5":     uinput.KeyF5,
	"F6":     uinput.KeyF6,
	"F7":     uinput.KeyF7,
	"F8":     uinput.KeyF8,
	"F9":     uinput.KeyF9,
	"F10":    uinput.KeyF10,
	"F11":    uinput.KeyF11,
	"F12":    uinput.KeyF12,
}
